### ISSUE TITLE
Footer infos

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#115]
Hey there!
There is currently no footer in the app. Would you like there to be one? And with what information?
We could link to the GitHub Repo, the Monstas, the Travis Foundation etc.
We probably also need an imprint of sorts, but maybe it's enough if we link to the one on the Foundation page. Thoughts @anikalindtner?

**Comment by saltinejustine** [comment]
Is there a mailing list for this application? Perhaps you could have a way for people to sign up and get updates on new features of the app?

Perhaps we could also include some "Help" links like, "How to draft a CoC" or other relevant links?

**Comment by anikalindtner** [comment]
@lislis I think we should put in there something like:  Travis Foundation I Made by Rubymonstas and link to the respective sites as well as to Github.

@saltinejustine there is none yet. a 'help' section would be good. A 'How to draft a CoC' is planned for the Foundation site :)

**Comment by alicetragedy** [comment]
:+1: on adding a footer. 
Adding links to Rubymonstas + the Foundation would definitely be great.
I also like the idea of a help section. (maybe for the future, as content is lacking right now)

By law, the Impressum should also be there (not sure if it's enough to link to the Foundation one, but I guess worst case scenario we can just copy it?). Also afaik there is [this](http://www.language-boutique.com/lost-in-translation-full-reader/impressum-or-imprint.html) ongoing discussion, in case any of you are language nerds :) (tl;dr: it should probably read "impressum" rather than "imprint")

**Comment by lisbethmarianne** [comment]
Thanks @ariaru
