### ISSUE TITLE
[UX] Phrasing in the apply form

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#127]
Hey there!

I noticed this on the apply form `Please fill out this form. Unless otherwise specified, all fields are required.`
Though this seems super logical, most users are more familiar with the `*` indicating mandatory fields and are confused if they get an error for what they think was an optional field.  

Nothing super bad though, just food for thought :)

**Comment by alicetragedy** [comment]
The first time I tested the app, I actually didn't read that part, and then got an error about some field I had not filled out 🙈 
(incidentally, I did not 'go back' and was stuck in `preview`, because the email confirmation field does not get shown there)

So maybe a further indication of the fields being mandatory would be a good idea (ie. using `*`)

**Comment by lisbethmarianne** [comment]
@alicetragedy Being stuck in preview, this is an old error, or does this still happen? You should not go to preview if you missed to fill out something.

**Comment by alicetragedy** [comment]
@lisbethmarianne I will test it locally again, see what happens, and open an issue if the error is still there. :+1:

**Comment by alicetragedy** [comment]
@lisbethmarianne would it be possible to still add the `*` as Lisa brought up above? @anikalindtner said the same thing when going through the forms again, so we feel it might be a good indicator of fields that need to be filled out.

**Comment by lisbethmarianne** [comment]
Done with #164
