### ISSUE TITLE
[bug] organizer email confirmation

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#130]
When I want to create a new event and try to submit the empty form, the email confirmation field disappears. 
Now I cannot enter the email confirmation and am not able to submit the form.

**Comment by lisbethmarianne** [comment]
Ah, now I understand what is happening! It only shows the email confirmation if the action_name is 'new'. I think we added that because there were some trouble with the edit action if we had it there. We can add 'preview' and this will fix it.

Good that you spotted that. I think it is the same thing that @alicetragedy mentioned in #127

**Comment by alicetragedy** [comment]
yes, I believe that's the same one. :+1:

**Comment by fidothe** [comment]
Fixed in #132
