### ISSUE TITLE
List events with diversity tickets with external application

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#168]
I think it would be nice if people can submit their events even if they handle the application by themselves. 

So we would show their event and have a link to their page where people can apply.

No idea how this would work technically. But maybe it is worth thinking about it? What do you think @anikalindtner and @alicetragedy

**Comment by anikalindtner** [comment]
I like the idea! I also have been thinking about how to 'sale' this, because i'd love for many conferences to be able to use this. and we just don't have the time to handle more than one conference at a time for now. Of course we can expand the team also project-based, but that's something Laura and I have to think about in the future. So yes, I'd love some kind of ability to use the app, but not have us handle the applications.

**Comment by alicetragedy** [comment]
I also love the idea of people being able to submit their events and handle the submissions themselves. I think it would give the app more reach and exposure.. and at the end of the day, it's better for everyone if more events do diversity tickets. :) 
Then we probably have to think about what that would imply in terms of architecture changes, for example adding roles/user types which have certain rights on their own events. I'm all for it! :+1:
