### ISSUE TITLE
Add VISA option

### ISSUE THREAD

**Issue by anikalindtner** [rubymonsters/diversity_ticketing#173]
We need a checkbox that says 'I would need a VISA' that people can tick or not. Is it possible to only add the checkbox to this event: https://diversitytickets.org/events/10 ? Probably not, right?

**Comment by anikalindtner** [comment]
also we'd need this by the end of the week. If you don't have time, @alicetragedy can take this on, we just need to ping her.

**Comment by lisbethmarianne** [comment]
We can add a column to applications 'visa_required' set to false as a default.
Then we can add a line 
if @event.id == 10
   show checkbox
end

and remove this after the event is done.

Or i think of something more permanent.

Anybody else has some thoughts?

**Comment by alicetragedy** [comment]
I think what you outlined above @lisbethmarianne can definitely be a "quick fix" for the first event, and then changed after that. by the way, since the visa is usually dependent on the nationality of the attendee rather than the country lived in, it would have to apply to both event.id == 10 and event.id == 9 (the two events that have a travel grant attached).

I think that in the future, we will have two ticket "types": the ticket-only, and the ticket+travel. each one has slightly different needs, and so I think that eventually we might want to somehow change the structure (for example using a Ticket Model or something). Some columns would then only be shown depending on the ticket type.

**Comment by lisbethmarianne** [comment]
If it is for event 9 and 10, that's much easier, then we just always add it if travel is funded.

**Comment by alicetragedy** [comment]
:+1:
