### ISSUE TITLE
error message at sign in is confusing, sign up link is hard to find

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#186]
When you at the sign in page, one could think it is the sign up page. 
So if you haven't signed up, you should get a message saying "you are not registered, please sign up".

Sign up link is hard to find, because it is only there at the sign in page (under the big green sign in button). There should be a dropdown with both links in the navbar.

Maybe hide all of the sign in / sign up links in navbar, until it has any function for non-admins.

**Comment by joecorcoran** [comment]
I'm in favour of hiding the links until they are useful for non-admins. Also, so I don't make a fool of myself again 😺

**Comment by ariaru** [comment]
:+1: 
And maybe later, when the links are useful, but applicants are still not supposed to sign up (only event organizers) we could have a dropdown with the headline "Event organizers" or sth like that. We could build that now, and just hide it.
And if we get to the point where it makes sense for applicants to sign up as well, we can make another dropdown "Applicants".

**Comment by mauditecandela** [comment]
@ariaru and @lisbethmarianne we have replaced the pop up for event organizers when they try to submit an event and haven't signed in yet. For applicants, we also have created profiles, but shouldn't be mandatory to sign in as we still want to give the opportunity to submit an application without registering. I think, due to these changes, we can close this issue. :)
