### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#200]
make twitter account for diversity tickets

app should post event to twitter when it gets approved // reminder shorty before deadline

**Comment by ferbsx** [comment]
@anikalindtner : Do you think it's necessary for Diversity tickets to have their own twitter account or would you want it to be connected to the travis foundation account?

If you want a new twitter account for this, then could you please make the Twitter account and give us the password and handle so we can make the connection? 
(Because we don't know which email the account should be made with)

Thank you <3
