### ISSUE TITLE
redirect https://www.diversitytickets.org to https://diversitytickets.org

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#230]
Go to http://www.diversitytickets.org/ and you'll get a not so nice Heroku error page.
We should redirect that to the 'real' page

**Comment by fidothe** [comment]
yeah, that would be good. Heroku docs for domain name are here: https://devcenter.heroku.com/articles/custom-domains#add-a-custom-domain-with-a-subdomain

How exactly to do this is a bigger question. There are a couple of approaches you could look at:

1. add a `before_action` to every controller that checks for www and redirects
2. add a piece of Rack middleware that does it without you having to modify the controllers
3. some clever monkeying with `routes.rb`

This is worth tackling sooner rather than later, and if someone wants to tackle it I can make myself available to help out...

**Comment by lisbethmarianne** [comment]
PR #234 solved this.
