### ISSUE TITLE
Reverse sorting for past events 

### ISSUE THREAD

**Issue by lislis** [rubymonsters/diversity_ticketing#289]
Hey there! 
I clicked on https://diversitytickets.org/past_events and right now it sorts these events from oldest (top) to newest (bottom).
I think sorting past events the other way around makes more sense.
If I  just scrolled through the list of upcoming events with open applications, then upcoming events with closed application I expect that the _past events_ section continues in the timeline. That would be the most recently passed events.
What do you think?

**Comment by lisbethmarianne** [comment]
I think yes, we should do it, but it seems it's not an easy fix. Since we have the two columns it will fill the first one first and then the second one. So it will show the last events on the top of the first column, but then show older events in the second column.

Ideally it would fill the columns in a way that the last event is in the first column, the second last is in the second column, the third last gets added under in the first column ...

I don't know if this is possible with css only. I've done it before with http://salvattore.com/.

What do you think @lislis?

**Comment by guainumbi** [comment]
Hi @lisbethmarianne and @lislis. I just came across this issue. We have since added a keyword and filter-search to the upcoming and past events page and it would be easily possible to order the past events by e.g. end_date. This would not fix the css/columns issue lisbethmarianne was referring to, but maybe combined with the search feature this could be an acceptable solution? What do you think? :)

**Comment by lislis** [comment]
@guainumbi that sounds like a reasonable solution :+1:  Do you want to work on this?

**Comment by guainumbi** [comment]
I can do it tomorrow! Thanks @lislis :)
