### ISSUE TITLE
What to do when self-organizing selection & application, but Diversity Tickets entry _is_ the application form

### ISSUE THREAD

**Issue by jancborchardt** [rubymonsters/diversity_ticketing#358]
We are handling both the selection and application process ourselves, and in the application details write:

> Then, send a mail to events@nextcloud.com with subject [Diversity ticket] YOUR NAME and a link to your contribution, whatever it is!

We wouldn’t like to use a Google form for this, so I wonder if it’s possible to accept email addresses for submissions too? Or if in this case the application details are enough? Putting [a mailto-link in the application details](https://github.com/nextcloud/server/wiki/Diversity-Tickets#application-details) results in an error "Application link is invalid".

Because if we put a section about that on the website it defeats the purpose a bit since we would like to link to Diversity Tickets there. (Sorry in advance because it might be an edge-case. It would be good to know what the best practice here is. :)

**Comment by lislis** [comment]
Ohai! I think having the app check for either a valid url or a valid email address is the most straight forward way here. 
Any objections @alicetragedy ?

**Comment by alicetragedy** [comment]
@lislis I think there's some implications to having your suggestion (which yes is straight-forward) or  @jancborchardt's suggestion (which was to directly put a mailto link in the field rather than just an email address) implemented. Because of the way diversity tickets is currently structured, a “listing-only” event will show the text “Apply at [conference name]” on a button in the event overview (see image below), not sure if from the user's perspective the expected behaviour would be that your email client opens. What would be a good way of solving that? 

<img width="541" alt="Screenshot 2019-04-10 at 16 08 35" src="https://user-images.githubusercontent.com/3143348/55885829-eb31fb00-5baa-11e9-8364-81b56ce9d3a8.png">

**Comment by alicetragedy** [comment]
I'm not necessarily against the “most straight forward way” though, just wanted to point out that this might have some side effects. For example, if only an email address is provided we might have to change the description placeholder text in the event form to point out the conference might need to give basic information about what is expected in the email application? It might get a bit messy — generally I think that having the conference provide some form of url instead (e.g. even just a “diversity tickets” section on their landing page to explain what the process will be like and what the expectations are) might still be preferable. This is still the most inclusive way, because you're making expectations explicit which would otherwise be implicit.

**Comment by lislis** [comment]
> because you're making expectations explicit which would otherwise be implicit.

That makes perfect sense :)

Since this case came up though, how about adding your explanation as an FAQ and a link from the form to that question with a label like *Why do I have to provide a link?* or something like that?

**Comment by alicetragedy** [comment]
@lislis I really like that idea! @jancborchardt do you think (from the conference organiser's perspective) this would be a good compromise for you? 

Would either of you be up for creating an issue so that we don't forget (and you're welcome to work on it if I don't get around to it, happy to review anything!)

**Comment by jancborchardt** [comment]
Since meanwhile we just created a page and looking back it seems a very specific issue, I don't know if we need to change anything. Especially also with all the points you brought up.

Having a page on the organizer side is quite important to raise awareness and make sure that the organizer is actually behind the effort. So now I'm just thinking that if no one else had this case before, there's probably nothing to be done?

**Comment by lislis** [comment]
> Having a page on the organizer side is quite important to raise awareness and make sure that the organizer is actually behind the effort.

I think just having this written down somewhere is :heavy_plus_sign: :heavy_plus_sign: :heavy_plus_sign:

**Comment by lislis** [comment]
PR open for comments #479 !
