### ISSUE TITLE
First version of applicants' web form

### ISSUE THREAD

**Issue by ariaru** [rubymonsters/diversity_ticketing#5]
- Routes
- Controller
- View
Form fields:
- Name/Nickname
- Email address
Based on conference organizer's specifications:
- Include 1-3 other form fields

**Comment by Powerglove** [comment]
Andrea and I are planning to work on this one, please join us if you have time: Thursday, 6 pm at Betahaus.

**Comment by wanaw-bln** [comment]
Today we ran into this error message after creating a controller for "application":
Circular dependency detected while autoloading constant ApplicationController

We thought this might be because we called our 2nd model "application" which is quite a common term in rails - so rails might get confused .
So we might have to think of a new name for the 2nd model?
Cheers, Johanna & Andrea
