### ISSUE TITLE
Validation messages should be improved

### ISSUE THREAD

**Issue by lisbethmarianne** [rubymonsters/diversity_ticketing#82]
too many messages, i.e. if you submit an application it says

Email can't be blank
Email is invalid

Is it possible to put them into one message?

**Comment by ferbsx** [comment]
This is not very friendly either.
When question 1 was left blank, you'd get this message, and if the second one is empty, you'd get the same message just with 2 instead of 1. 

![screen shot 2016-01-11 at 7 59 49 pm](https://cloud.githubusercontent.com/assets/11502220/12245526/565eafde-b8a9-11e5-8ff9-a7975bb65166.png)

**Comment by lisbethmarianne** [comment]
done with #145
