### ISSUE TITLE
Raise barrier for applicants

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/diversity_ticketing#83]
Right now it's too easy to apply. Someone could apply with a bunch of different emails, and get a higher chance.
and since it's not too hard to apply, everyone would apply even if they can't make it.

eg; 
- why do you deserve the ticket? 
- why do you want to go to this conference?

**Comment by lisbethmarianne** [comment]
@anikalindtner What do you think? At the moment the form for applicants only has Name and Email.

**Comment by anikalindtner** [comment]
@lisbethmarianne yes, there will be more questions, definitely! I have the form, which i want to use as a google doc - I´ll paste it here on the weekend!

**Comment by anikalindtner** [comment]
Text fields:

+ Tell us why you want to attend //event x// 
+ What do you look forward to learning at //event x// ?
+ What do you do? 
+ Please share with us why you're applying for a diversity ticket. (1-2 sentences is enough, please only share what you're comfortable with)

+ Your Name 
+ Your Email 

Checkbox: 

+ Terms of conditions: 
This diversity program is aimed to help underrepresented groups in tech to attend and lowering the barriers for them. This includes but isn’t limited to: women, people of color, LGBTQIA+ people, and disabled people. Your privacy, details, answers remain protected, we will raffle out the tickets. We will not share any data with those, who sponsor these tickets. This application is for one conference ticket only. The ticket includes 
+ ? travel costs
+ ? admission to the conference itself, 
+ ? catering for the day of the conference,
+ ? and admission to the parties organised for the conference attendees, speakers, and staff.

 All attendees, speakers, sponsors and staff at //Event x // are required to agree with the Code of Conduct of the event. Organizers will enforce this code throughout the event //link to code of conduct of event//. 
---

? -> these fields need to be defined by the organizers who submit the event. As well as //fields// have to be automatically filled out taking in the data of the submission of the event.

**Comment by Powerglove** [comment]
Hey Anika,

we think the second question is redundant and the third too personal. The first question already contains what you want to learn and asking for a profession might make people feel unconfortable.
What do you think?

Dayana, Katrin and Johanna

**Comment by anikalindtner** [comment]
heja, thanks for the feedback! 

I agree, that we can combine question 1 and 2 into: why do you want to attend EVENT X  and what especially do you look forward to learning? 

(reason behind is that why can be different (a.k.a. making new business contacts) to learning (which then means they actually have to have a look at the program and the topics that will be presented)).

As for the 3rd question: I've talked with some people before coming up and actually using that question (for two conferences). I think the part "Please only share what you are comfortable with" can be made a bit more prominent, but we have no other way of finding out if that person actually "qualifies" for a diversity ticket. In my experience we had sooo so many white heterosexual men apply, that this is necessary to make sure the ticket doesn't go to a person that doesn't understand what diversity ticket means. Because other than the name (which also can be super ambiguous) we have no other info. That's why we need this question. But to make sure, that people really only write down what they deem not too personal, we should highlight the sentence: "Please only share what you're comfortable with.".

**Comment by lisbethmarianne** [comment]
@anikalindtner When you talk about the 3rd question do you mean "What do you do?" or the next one? We would like to skip "What do you do?".

**Comment by anikalindtner** [comment]
@lisbethmarianne i mean the "please share with us why you are applying for a diversity ticket"

**Comment by lisbethmarianne** [comment]
@anikalindtner  a question about what you wrote in the Terms: at the moment we have Ticket, Travel and Accommodation what events can offer to pay for the diversity ticket. Should we add catering and parties?

**Comment by anikalindtner** [comment]
@lisbethmarianne I don't think we need to add this to the offers, but this just goes without saying that this is always included (that's why we put it in the terms and conditions).
